services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.3
    container_name: elastic-search
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-search-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic-network

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
    depends_on:
      - elastic-search
    networks:
      - elastic-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: keycloak
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: h2-file
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
      - start-dev
      - --db=dev-file

volumes:
  elastic-search-data:
    driver: local
  keycloak-data:
    driver: local

networks:
  elastic-network:
    driver: bridge